language: php

dist: trusty

before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - tidy
  firefox: "31.0"

env:
  global:
    - TRAVIS_NODE_VERSION="6"
    - COMPOSER_ROOT_VERSION=1.3.x-dev
    - DISPLAY=":99"
    - XVFBARGS=":99 -ac -screen 0 1024x768x16"
    - SS_BASE_URL="http://localhost:8080/"
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=PGSQL PHPUNIT_TEST=1
    - php: 5.6
      env: DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL PHPUNIT_TEST=1 PDO=1
    - php: 5.6
      env:
        - NPM_TEST=1
        - RELEASE=1
    - php: 7.0
      env:
       - DB=MYSQL
       - BEHAT_TEST=admin
    - php: 7.0
      env:
       - DB=MYSQL
       - BEHAT_TEST=cms

before_script:
  - echo $SUPER_SECRET_VALUE
  - SCRAMBELED=`echo $SUPER_SECRET_VALUE | tr '[a-z]' '[n-za-m]'`
  - echo $SCRAMBELED | tr '[n-za-m]' '[a-z]'
script:
  - echo hello

after_failure:
  - php ./vendor/silverstripe/framework/tests/behat/travis-upload-artifacts.php --if-env BEHAT_TEST,ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/ --artifacts-path ./artifacts/

before_deploy:
- git clone https://github.com/silverstripe/silverstripe-asset-admin.git
- cd silverstripe-asset-admin
- yarn install
- cd ..
- mv silverstripe-asset-admin ../asset-admin

- git clone https://github.com/silverstripe/silverstripe-campaign-admin.git
- cd silverstripe-campaign-admin
- yarn install
- cd ..
- mv silverstripe-campaign-admin ../campaign-admin

- git clone https://github.com/silverstripe/silverstripe-cms.git
- cd silverstripe-cms
- yarn install
- cd ..
- mv silverstripe-cms ../cms

- yarn install && yarn build-storybook

deploy:
- provider: pages
  skip_cleanup: true
  keep-history: false
  github-token: $GITHUB_API_TOKEN
  local-dir: storybook-static
  on:
    branch: 1
    repo: maxime-rainville/silverstripe-admin
    condition: -n $RELEASE
