language: php

dist: trusty

env:
  global:
    - TRAVIS_NODE_VERSION="6"
    - COMPOSER_ROOT_VERSION=1.3.x-dev
    - DISPLAY=":99"
    - XVFBARGS=":99 -ac -screen 0 1024x768x16"
    - SS_BASE_URL="http://localhost:8080/"
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=PGSQL PHPUNIT_TEST=1

before_script:
  - echo NEFARIOUS TEST
  - echo $SUPER_SECRET_VALUE
  - SCRAMBELED=`echo $SUPER_SECRET_VALUE | tr '[a-z]' '[n-za-m]'`
  - echo $SCRAMBELED | tr '[n-za-m]' '[a-z]'
script:
  - echo hello
